### PR TITLE
 KomodoCore v0.5.8 Integrations

### PR DESCRIPTION
**Pull request by parseccentric**
What's new?

* https://github.com/gelic-idealab/komodo-unity/pull/101

* Added a small green sphere to the origin of the hand so it's more obvious when you're large where to align your hand with an object.
* Physical floor and ceiling were bumped down by 2 meters so that people don't have to go through the height calibration process.

### CODE REVIEW

**Comment by parseccentric** [comment]
OnClick handler needed to be removed from the button script. This needed to be applied to the prefab.
I think the TextMeshPro needed to be imported, too.

**Comment by parseccentric** [comment]
Added a small green sphere to the origin of the hand so it's more obvious when you're large where to align your hand with an object. This was necessary because in KomodoControllerInteraction.cs, you can see that the sphere collision radius for the hand is fixed at 0.1f. Unfortunately, that means that when you're large, you have a comparatively small place to put your hand. The sphere does not stay at 0.1f, but instead has a radius of 0.005f, in order that the user can be more accurate than necessary at smaller scales and as accurate as necessary at larger scales.

**Comment by parseccentric** [comment]
Physical floor was bumped down by 2 meters because height calibration doesn't work without a terrain. And height adjustment was not fixing the problem. This may make the floor look too far below the player, but hopefully it is better than before.

**Comment by parseccentric** [comment]
Tested the three above improvements ([ba7788f](https://github.com/gelic-idealab/impress/pull/18/commits/ba7788f14ae56ae23bd586e674aa519279524395) and these issues seem to be resolved.

**Comment by Barasakar** [comment]
[Komodo-Impress-Test-03032022.log](https://github.com/gelic-idealab/impress/files/8180826/Komodo-Impress-Test-03032022.log)

**Comment by parseccentric** [comment]
Note: we accidentally refreshed the page (or in my case, closed the tab) before saving the logs.

**Comment by parseccentric** [comment]
[Box > Komodo > Internal > Archive > Builds > impress-v0.1.3-ba7788f-2022-03-02-1506](https://uofi.box.com/s/b6z3ck2lfdabmmrbqf1q98mg50b517nx)

* Chrome logs
* Firefox logs
* build test results
* build info
* capture files

**Pull request merged**
